substitutions:
  devicename: baxiheatpumpatom
  friendly_name: "Baxi Heat Pump Atom"

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  project:
    name: "Liberdade4.UIMBaxiConnect-GTW08"
    version: "1.0"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino # esp-idf

# Wi-Fi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .iot.liberdade4.com
  fast_connect: true
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_ap_password

captive_portal:

web_server:
  port: 80

# Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# Logs (baud_rate: 0 frees UART for Modbus)
logger:
  level: INFO
  baud_rate: 0

# Integrated status LED on AtomS3
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO35
    num_leds: 1
    chipset: ws2812
    name: "${friendly_name} Status LED"
    id: status_led
    effects:
      - pulse:
          name: "Pulse"
      - strobe:
          name: "Strobe"

# UART configuration for Modbus RS485 via GTW-08
uart:
  id: modbus_uart
  tx_pin: GPIO6
  rx_pin: GPIO5
  baud_rate: 9600
  stop_bits: 1
  parity: NONE

# Modbus RTU
modbus:
  id: modbus1
  uart_id: modbus_uart
  send_wait_time: 250ms

modbus_controller:
  - id: gtw08_controller
    address: 0x64              # GTW-08 default Modbus address (100 decimal = 0x64 hex)
    modbus_id: modbus1
    command_throttle: 200ms
    setup_priority: -10
    update_interval: 15s
    offline_skip_updates: 5  # Skip updates if no response

# Heat pump sensors via GTW-08 (ONLY VALID REGISTERS - See GTW-08 Manual)
sensor:
  # Flow temperature (Register 400 - AM016)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Flow Temperature"
    id: temp_flow
    address: 400
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Return temperature (Register 401 - AM018)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Return Temperature"
    id: temp_return
    address: 401
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Outdoor temperature (Register 384)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Outdoor Temperature"
    id: outdoor_temp
    address: 384
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Heat pump flow temperature (Register 403 - HM001)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} HP Flow Temperature"
    id: hp_temp_flow
    address: 403
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Heat pump return temperature (Register 404 - HM002)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} HP Return Temperature"
    id: hp_temp_return
    address: 404
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # DHW Flow setpoint (Register 408 - DM004)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} DHW Setpoint"
    id: dhw_setpoint_read
    address: 408
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Water pressure (Register 409 - AM019)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Water Pressure"
    id: water_pressure
    address: 409
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "bar"
    device_class: pressure
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Error code (Register 410 - for diagnostics)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Error Code"
    id: error_code
    address: 410
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic

  # System status (Register 411 - AM012 - Main appliance status)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} System Status Code"
    id: system_status_code
    address: 411
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic

  # Sub status (Register 412 - AM014 - Sub status)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Sub Status Code"
    id: sub_status_code
    address: 412
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic

  # System power output (Register 413 - AM024)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Power Output"
    id: power_output
    address: 413
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 0

  # WiFi signal
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  # Uptime
  - platform: uptime
    name: "${friendly_name} Uptime"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"

binary_sensor:
  # Integrated button
  - platform: gpio
    pin:
      number: GPIO41
      inverted: true
    name: "${friendly_name} Button"
    on_press:
      then:
        - light.toggle: status_led

# Switch commands
switch:
  # System ON/OFF (Register 259)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} ON/OFF"
    address: 259
    register_type: holding
    use_write_multiple: false
    on_turn_on:
      then:
        - light.turn_on:
            id: status_led
            brightness: 100%
            red: 0%
            green: 0%
            blue: 100%
    on_turn_off:
      then:
        - light.turn_on:
            id: status_led
            brightness: 30%
            red: 100%
            green: 50%
            blue: 0%

# Number controls
number:
  # System power setpoint (Register 256)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Power Setpoint"
    address: 256
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "%"
    mode: box
    entity_category: config

  # Flow temperature setpoint (Register 257)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} Flow Temperature Setpoint"
    address: 257
    register_type: holding
    value_type: U_WORD
    min_value: 20
    max_value: 80
    step: 1
    unit_of_measurement: "°C"
    mode: box
    entity_category: config

  # DHW temperature setpoint (Register 408)
  - platform: modbus_controller
    modbus_controller_id: gtw08_controller
    name: "${friendly_name} DHW Temperature Setpoint"
    address: 408
    register_type: holding
    value_type: U_WORD
    min_value: 30
    max_value: 60
    step: 1
    unit_of_measurement: "°C"
    mode: slider
    entity_category: config
