substitutions:
  devicename: baxiheatpumpatom
  friendly_name: "Baxi Heat Pump Atom"

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  project:
    name: "Liberdade4.BaxiModbusIntegration"
    version: "1.0"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino # esp-idf

# Wi-Fi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .iot.liberdade4.com
  fast_connect: true
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_ap_password

captive_portal:

web_server:
  port: 80

# Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# Logs (baud_rate: 0 frees UART for Modbus)
logger:
  level: INFO
  baud_rate: 0

# Integrated status LED on AtomS3
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO35
    num_leds: 1
    chipset: ws2812
    name: "${friendly_name} Status LED"
    id: status_led
    effects:
      - pulse:
          name: "Pulse"
      - strobe:
          name: "Strobe"

# UART configuration for Modbus RS485
uart:
  id: modbus_uart
  tx_pin: GPIO2    # Grove SDA (yellow) on AtomS3
  rx_pin: GPIO1    # Grove SCL (white) on AtomS3
  baud_rate: 9600
  stop_bits: 2
  parity: NONE

# Modbus RTU
modbus:
  id: modbus1
  uart_id: modbus_uart
  send_wait_time: 250ms

modbus_controller:
  - id: baxi_controller
    address: 0x01              # Modbus slave address (confirm with controller)
    modbus_id: modbus1
    command_throttle: 200ms
    setup_priority: -10
    update_interval: 15s       # Poll every 15 seconds

# Heat pump sensors
sensor:
  # Main temperatures
  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} Flow Temperature"
    id: temp_flow
    address: 0x4E29           # Example address - confirm with Modbus map
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1         # Converts to °C if needed
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x > 0;'
            then:
              - light.turn_on:
                  id: status_led
                  brightness: 50%
                  red: 0%
                  green: 100%
                  blue: 0%

  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} Return Temperature"
    id: temp_return
    address: 0x4E2A           # Example address
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Outdoor temperature (if available)
  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} Outdoor Temperature"
    address: 0x4E20           # Example address
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # DHW setpoint
  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} DHW Setpoint"
    address: 0x4F10           # Example address
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Diagnostic sensors (WiFi/System)
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"

# Binary states
binary_sensor:
  # Integrated button
  - platform: gpio
    pin:
      number: GPIO41
      inverted: true
    name: "${friendly_name} Button"
    on_press:
      then:
        - light.toggle: status_led

  # Compressor state
  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} Compressor Active"
    address: 0x0001           # Example address
    register_type: coil

  # Active alarm
  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} Alarm Active"
    address: 0x0002           # Example address
    register_type: coil

  # Cooling mode
  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} Cooling Mode"
    address: 0x0003           # Example address
    register_type: coil

# Switch commands
switch:
  # Heat pump ON/OFF
  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} ON/OFF"
    address: 0x0001           # Example address
    register_type: coil
    use_write_multiple: false
    on_turn_on:
      then:
        - light.turn_on:
            id: status_led
            brightness: 100%
            red: 0%
            green: 0%
            blue: 100%
    on_turn_off:
      then:
        - light.turn_on:
            id: status_led
            brightness: 30%
            red: 100%
            green: 50%
            blue: 0%

# Number controls
number:
  # Heating setpoint
  - platform: modbus_controller
    modbus_controller_id: baxi_controller
    name: "${friendly_name} Heating Setpoint"
    address: 0x5001           # Example address
    register_type: holding
    value_type: S_WORD
    min_value: 15
    max_value: 35
    step: 0.5
    unit_of_measurement: "°C"
    mode: box
    multiply: 10              # If controller expects value × 10

